apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: {{ .Values.frontendsvc.spec.type }}
  selector:
    app: {{ .Values.frontendsvc.selector.app }}
  ports:
  - port: {{ .Values.frontendsvc.ports.port | default 5175 }}
    targetPort: {{ .Values.frontend.container.port | default 5173 }}
    nodePort: {{ .Values.frontendsvc.ports.nodePort | default 31000 }}