apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.redis.metadata.name}}
  labels:
    app: {{.Values.redis.metadata.name}}
spec:
  replicas: {{.Values.redis.deployment.replicas}}   
  selector:
    matchLabels:
      app: {{.Values.redis.labels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.redis.labels.app}}
    spec:
      containers:
      - name: {{.Values.redis.container.name}}  
        image: "{{.Values.redis.container.image.repository}}:{{.Values.redis.container.image.tag}}"   
        ports:
        - containerPort: {{.Values.redis.container.port}}   