# frontend deployment
frontend:
  metadata:
    name: frontend-im

  
  deployment:
    replicas: 1
  
  
  container:
    name: frontend-container
    image:
      repository: shreybatra/sample-frontend
      tag: latest
    port: 5173

 
  labels:
    app: frontend

#frontend service    
frontendsvc:
  ports:
    nodePort: 31000
    port: 5175

  spec:
    type: NodePort  
  selector:
    app: frontend



#configmap
configmap:
  metadata:
    name: config
  data:
    BACKEND_URL: "http://backend-svc:8000"
    REDIS_URI: "redis://redis-svc:6379"



#backend deployment
backend:
  metadata:
    name: backend-deployment

  
  deployment:
    replicas: 1

  labels:
    app: backend

  
  container:
    name: backend-container
    image:
      repository: shreybatra/sample-backend
      tag: latest
    port: 8000




# backend service
backendsvc:
  metadata:
    name: backend-svc
  spec:
    type: ClusterIP
  selector:
    app: backend


#redis-deployment

# General parameters
redis:
  metadata:
    name: redisdeploy

  
  deployment:
    replicas: 1

  labels:
    app: redisdb

  
  container:
    name: redis-container
    image:
      repository: redis
      tag: latest
    port: 6379

# redis service

redissvc:
  metadata:
    name: redis-svc
  spec:
    type: ClusterIP
  selector:
    app: redisdb