apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backendsvc.metadata.name}}
spec:
  type: {{.Values.backendsvc.spec.type}}
  selector:
    app: {{.Values.backendsvc.selector.app}}
  ports:
  - port: {{ .Values.backend.container.port }}
    targetPort: {{ .Values.backend.container.port }}