apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.metadata.name }}
  labels:
    app: {{ .Values.backend.metadata.name }}
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.backend.container.name }}
        image: "{{ .Values.backend.container.image.repository }}:{{ .Values.backend.container.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.container.port }}
        env:
        - name: REDIS_URI
          valueFrom:
            configMapKeyRef:
              name: config
              key: REDIS_URI