apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.metadata.name }}
data:
  BACKEND_URL: "{{ .Values.configmap.data.BACKEND_URL }}"
  REDIS_URI: "{{ .Values.configmap.data.REDIS_URI }}"

