apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.metadata.name }}
  labels:
    app: {{ .Values.frontend.metadata.name }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.container.name }}
        image: "{{ .Values.frontend.container.image.repository }}:{{ .Values.frontend.container.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.container.port }}
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: BACKEND_URL