apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redissvc.metadata.name}}
spec:
  type: {{.Values.redissvc.spec.type}}
  selector:
    app: {{.Values.redissvc.selector.app}}
  ports:
  - port: {{ .Values.redis.container.port }}
    targetPort:  {{ .Values.redis.container.port }}